=== Dobyll/Sit_Web_Guide_Tourisme/XML/site.dtd
<!ENTITY % format "(24h|AM|PM)" >

		<!-- structure de l'élément racine touristique -->
		<!ELEMENT touristique (pays, informationgeneral, lieuxtouristiques)>

		<!-- informations sur le pays -->
		<!ELEMENT pays (nompays, imagepays+, capitale, langueofficielle, devise, continent)>

		<!ELEMENT nompays (#PCDATA)>

		<!ELEMENT imagepays EMPTY>
		<!ATTLIST imagepays
				id ID #IMPLIED
				title CDATA #REQUIRED
				src CDATA #REQUIRED
				alt CDATA #REQUIRED >

		<!ELEMENT capitale (#PCDATA)>
		<!ELEMENT langueofficielle (#PCDATA)>
		<!ELEMENT devise (#PCDATA)>
		<!ELEMENT continent (#PCDATA)>

		<!ELEMENT informationgeneral (descriptiongeographique, culture, tourisme)>
		<!ELEMENT descriptiongeographique (#PCDATA) >
		
		<!ELEMENT culture (demographie, religion, evenements, cuisine, arts)>

		<!ELEMENT demographie (#PCDATA)>
		<!ATTLIST demographie
				id ID #REQUIRED>


		<!ELEMENT religion (#PCDATA)>
		<!ATTLIST religion
				id ID  #REQUIRED>

		<!ELEMENT evenements (#PCDATA)>
		<!ATTLIST evenements
		       id ID  #REQUIRED>
		 


		<!ELEMENT cuisine (#PCDATA)>
		<!ATTLIST cuisine
				id ID  #REQUIRED>


		<!ELEMENT arts (#PCDATA)>
		<!ATTLIST arts
				id ID  #REQUIRED>


		<!ELEMENT tourisme (#PCDATA)>

		<!-- les lieux touristiques à visiter -->
		<!ELEMENT lieuxtouristiques (lieutouristique+)>

		<!-- description du lieu -->
		<!ELEMENT lieutouristique (nom, imagelieu+, localisation, histoire, activites?)>
		<!ATTLIST lieutouristique
		        id ID #REQUIRED
				risque (faible|modere|eleve) #REQUIRED>

		<!ELEMENT nom (#PCDATA)>

		<!ELEMENT imagelieu  EMPTY>
		<!ATTLIST imagelieu
		        id ID #IMPLIED
				title CDATA #REQUIRED
				src CDATA #REQUIRED
				alt CDATA #REQUIRED > 

		<!ELEMENT localisation (ville, region, adresse?)>
		<!ELEMENT ville (#PCDATA)>
		<!ELEMENT region (#PCDATA)>
		<!ELEMENT adresse (#PCDATA)>

		<!-- partie historique du lieu -->
		<!ELEMENT histoire (importanceculturelle, anecdote?)>

		<!ELEMENT importanceculturelle (#PCDATA)>
		<!ATTLIST importanceculturelle
				id ID #IMPLIED 
				niveau (important|mineur) #REQUIRED>

		<!ELEMENT anecdote (#PCDATA)>

		<!-- les activités associées au lieu touristique ou ses alentours -->

		<!ELEMENT activites (activite*)>
		<!ELEMENT activite (nomactivite, imageactivite+, descriptionactivite, horaires?, duree?, prix*, prevention*)>
		<!ATTLIST activite
				id ID #REQUIRED
				type (culturelle|sportive|historique|ludique|autre) #REQUIRED>

		<!ELEMENT nomactivite (#PCDATA)>

		<!ELEMENT imageactivite EMPTY>
		<!ATTLIST imageactivite
				id ID #IMPLIED
				title CDATA #REQUIRED
				src CDATA #REQUIRED
				alt CDATA #REQUIRED >

	    <!-- description de l'activité -->
		<!ELEMENT descriptionactivite (#PCDATA) >

		<!--les horaires -->
		<!ELEMENT horaires (ouverture, fermeture)>
		<!ATTLIST horaires
				type (normal|weekend|ferie)  #REQUIRED
				saison (ete|hiver|automne|printemps|all) #REQUIRED >

		<!ELEMENT ouverture (#PCDATA)>
		<!ATTLIST ouverture
				type %format; #REQUIRED>

		<!ELEMENT fermeture (#PCDATA)>
		<!ATTLIST fermeture
				type %format; #REQUIRED>

		<!ELEMENT duree (#PCDATA)>

		<!ELEMENT prix (#PCDATA)>

		<!ELEMENT prevention (#PCDATA)>
		<!ATTLIST prevention
				id ID #REQUIRED  >

=== Dobyll/Sit_Web_Guide_Tourisme/XML/Cameroun.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE touristique SYSTEM "site.dtd">
<touristique>
    <pays>
        <nompays>Cameroun</nompays>
        <imagepays src="../Images/drapeau-cameroun.webp" alt="Drapeau du Cameroun" title="" />
        <imagepays src="../Images/cameroun_carte.jpg" alt="carte du Cameroun" title=""/>
        <capitale>Yaoundé</capitale>
        <langueofficielle>Français, Anglais</langueofficielle>
        <devise>Franc CFA</devise>
        <continent>Afrique</continent>
    </pays>
    <informationgeneral>
        <descriptiongeographique>
            Le Cameroun, situé au cœur de l'Afrique centrale, offre une géographie d'une grande diversité. Bordé par l'océan Atlantique
            à l'ouest, il partage des frontières avec le Nigeria, le Tchad, la République centrafricaine, le Congo, le Gabon et la Guinée
            équatoriale. Le pays est marqué par des montagnes volcaniques, comme le Mont Cameroun, des plateaux verdoyants, des forêts
            tropicales et des savanes sèches au nord. Cette variété de paysages, couplée à un climat tropical et équatorial, fait du
            Cameroun un véritable carrefour naturel riche en biodiversité.
        </descriptiongeographique>
        <culture>
            <demographie id="demographie">
                Le Cameroun compte aujourd’hui entre 28 et 30 millions d’habitants. Il se distingue par une très grande diversité ethnique, avec
                plus de 250 groupes différents répartis sur l’ensemble du territoire. Cette diversité ethnique se reflète aussi dans la langue,
                puisque, outre les deux langues officielles — le français et l’anglais — on y parle plus de 200 langues locales. Le pidgin english,
                une langue créole à base d’anglais, est également couramment utilisé dans les régions anglophones. La population camerounaise
                est très jeune : plus de la moitié a moins de 25 ans, ce qui fait du pays une nation pleine de potentiel humain pour l’avenir.
            </demographie>
            <religion id="religions">
                La religion joue un rôle central dans la société camerounaise. Le christianisme est majoritaire, représentant environ 70 à 75 % de
                la population. L’Église catholique est très influente, aux côtés de nombreuses Églises protestantes, évangéliques et pentecôtistes.
                L’islam, quant à lui, regroupe environ 20 % des croyants, principalement dans les régions du Nord, de l’Extrême-Nord et de l’Adamaoua.
                Les religions traditionnelles africaines restent présentes et souvent pratiquées en parallèle des grandes religions monothéistes.
                Le syncrétisme religieux est courant, avec des croyances et rituels hérités des ancêtres qui cohabitent avec les cultes chrétiens
                ou musulmans.
            </religion>
            <evenements id="evenements">
                Le Cameroun célèbre plusieurs événements majeurs tout au long de l’année. La fête de l’unité, le 20 mai, est la principale
                célébration nationale, marquant l’unification du pays en un État centralisé en 1972. La fête de la jeunesse, le 11 février,
                est également très suivie, notamment dans les écoles et les universités. Sur le plan culturel, plusieurs festivals traditionnels
                rythment la vie des communautés : le Ngondo, à Douala, est une grande fête des peuples Sawa avec des cérémonies sur le fleuve
                Wouri ; le festival Nyem-Nyem à Ngaoundéré célèbre les traditions peules ; et le FESTAC, festival national des arts et de la
                culture, met en avant la richesse artistique camerounaise. Sur le plan politique, le pays est marqué par une stabilité relative
                mais aussi par des tensions, en particulier dans les régions anglophones. Le président Paul Biya est au pouvoir depuis 1982, ce
                qui suscite à la fois soutien et contestation.
            </evenements>
            <cuisine id="cuisine">
                La cuisine camerounaise est aussi variée que sa population. Chaque région a ses spécialités, influencées par les traditions locales,
                les produits du terroir et les cultures ethniques. Dans le Centre et le Sud, on retrouve des plats comme le ndolé, une sauce à base
                de feuilles amères (vernonia), souvent cuisinée avec des arachides, du poisson fumé ou des crevettes. Dans l’Ouest, chez les Bamiléké,
                on aime les mets consistants comme le koki (gâteau de haricots cuits à la vapeur dans des feuilles de bananier), les taros sauce jaune
                ou le poisson braisé accompagné de bâton de manioc. Au Nord, la cuisine est influencée par la culture peule et musulmane. On y mange
                souvent du bouillon de viande, du mil (en couscous ou bouillie), ou du foléré (boisson d’hibiscus). Le sauté de viande ou le kilichi
                (viande séchée épicée) sont aussi très appréciés. Dans les zones côtières, les plats à base de poissons et fruits de mer abondent,
                notamment le mbongo tchobi, une sauce noire épicée préparée avec du poisson.
                Les Camerounais aiment manger épicé, et les condiments maison sont rois : piments, ail, gingembre, oignons et épices locales sont
                omniprésents. En boisson, on retrouve des jus naturels comme le bissap (jus de fleurs d’hibiscus), le gingembre, ou des bières
                locales comme la Castel, la 33 Export ou la Kadji.
            </cuisine>
            <arts id="arts">
                Le Cameroun est une terre de créativité. La musique y tient une place importante, avec des genres comme le makossa (originaire de
                Douala), le bikutsi (du Centre), l’assiko, ou encore le bend-skin. Des artistes comme Manu Dibango, Richard Bona, Charlotte Dipanda,
                ou encore Petit Pays ont marqué la scène musicale nationale et internationale. Dans le domaine du cinéma, le Cameroun se développe
                avec des réalisateurs comme Jean-Pierre Bekolo ou Bassek Ba Kobhio, tandis que les séries et films produits localement gagnent en
                popularité sur les plateformes numériques. La littérature camerounaise est également riche, portée par des figures comme Mongo Beti,
                Calixthe Beyala, ou encore Léonora Miano. Côté arts visuels, des artistes contemporains comme Barthélémy Toguo ou Pascale Marthine
                Tayou exposent dans les plus grandes galeries du monde. Enfin, la mode camerounaise prend aussi de l’ampleur, avec des stylistes
                talentueux qui modernisent les tissus traditionnels pour en faire des pièces uniques.
            </arts>
        </culture>
        <tourisme>
            Le Cameroun, souvent appelé "l'Afrique en miniature", est une destination touristique incontournable grâce à sa diversité géographique,
            culturelle et ethnique. Entre ses plages bordées par l'océan Atlantique, ses montagnes majestueuses, ses forêts tropicales luxuriantes
            et ses savanes, le pays offre une multitude de paysages à explorer. Les visiteurs peuvent y découvrir une richesse unique, allant de
            la faune sauvage dans ses parcs nationaux, comme le parc de Waza, à la vibrante culture locale à travers ses marchés, festivals et
            traditions ancestrales. Le Cameroun est un lieu où les amoureux de la nature, les passionnés d'aventure et les curieux de cultures
            diverses trouveront de quoi nourrir leurs rêves d'évasion.
        </tourisme>

    </informationgeneral>

    <lieuxtouristiques>
        <lieutouristique id="lt1" risque="faible">
            <nom>Limbé et le Mont Cameroun</nom>
            <imagelieu src="../Images/limbe.jpg" alt="Village camerounais" title="https://generationvoyage.fr/endroits-visiter-cameroun/"/>
            <localisation>
                <ville>Buea</ville>
                <region>Sud-Ouest</region>
                <adresse>Mont Cameroun, Buea</adresse>
            </localisation>
            <histoire>
                <importanceculturelle niveau="important">
                    Limbé, montagne volcanique toujours en activité, jouxte les pentes mémorables du mont Cameroun. Malgré son origine volcanique,
                    la région n’en reste pas moins un creuset fertile de plantes, jardins et cascades d’eau. Quant au mont Cameroun, plus haut sommet
                    du pays avec ses 4 000 mètres et quelques d’altitude, il se laisse volontiers approcher par les amateurs de randonnée. L’ascension
                    se déroule entre forêts équatoriales épaisses et immenses prairies subalpines.
                </importanceculturelle>
                <anecdote>Le mont est encore un volcan actif avec des éruptions occasionnelles.</anecdote>
            </histoire>
            <activites>
                <activite id="a1" type="sportive">
                    <nomactivite>Randonnée sur le Mont Cameroun</nomactivite>
                    <imageactivite title="https://www.mickaelmussard.fr/randonnee/" src="../Images/Randonnée.jpg" alt="Randonnée"/>
                    <descriptionactivite>
                        Une randonnée exigeante mais gratifiante à travers la forêt tropicale et les champs de lave. Vous pouvez effectuer la montée et
                        la redescente en une journée ou bien passer une nuit dans un des chalets jonchés à plus de 2 000 mètres d’altitude. Choc thermique
                        assuré mais expérience fantastique garantie. Toutefois, l’ascension est globalement musclée : 27 kilomètres aller-retour. Les
                        novices se contenteront donc de crapahuter au pied de la montagne.
                    </descriptionactivite>
                    <horaires type="normal" saison="all">
